### ISSUE TITLE
Store card information with service

### ISSUE THREAD

**Issue by aseigo** [swelham/cashier#6]
Services such as PayPal and Stripe provide ways to store a customer's credit card information securely with the service. It would be nice to have API in Gateways supporting storing/deleting such records.

**Comment by swelham** [comment]
:+1:

Work items inolved
* [x] Add `store` and `unstore` functions to base gateway
* [x] Implement `store` and `unstore` functions on all gateways
* [x] Update payment methods on all gateways to accept either a `card` or `card_id` for payment

**Comment by aseigo** [comment]
Awesome, thanks! 

I didn't have the time I hoped for this weekend and this week I am away .. but when I am back in think I will take a stab at a stripe gateway. Great to see this project moving, having a complete and maintained solution for payment is really important for the ecosystem IMHO...

**Comment by swelham** [comment]
I agree, without it I feel the language could be ruled out of many areas of business that it could thrive in.

Definitely take a stab at the stripe gateway if you get time, I can do with all the help available! :smile:
