### ISSUE TITLE
Common response format

### ISSUE THREAD

**Issue by swelham** [swelham/cashier#7]
Currently there isn't a common response format returned from the `cashier` module that would cleanly work across payment providers.

The aim of this issue is for open discussion and suggestions on what data is commonly required by the client across payment providers.

To set some context, currently calling `Cashier.purchase(123, some_card, opts)` with success will return `{:ok, data}`. In this case `data` is just the decoded result that was returned from the payment provider. In order for the client to make use of the result, it would have to know which gateway was used for that request.

The result of this would mean clients who may not care which gateway handled the request or just need to generically log which gateway was used will be forced into detecting this manually and removes the purpose of having a common interface into the gateways.

The response needs to contain common results about the request and provide a way to identify which gateway handled the request. It should also return the raw data received from the payment provider for use cases that may fall outside of the common functionality of cashier.

**Comment by zubairshokh** [comment]
Can we have the understandable documentation or the usage, perhaps a simple example to use the library. Thank you

**Comment by swelham** [comment]
Yes documentation and examples are on the todo list, you can watch these [issues](https://github.com/swelham/cashier/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) if you wish to track this.

I do aim to get these examples up sooner rather than later, if nothing else at least some small details on the readme in the immediate future.

**Edit**: I have now updated the [readme](https://github.com/swelham/cashier/blob/master/README.md#usage) with some basic usage examples
